spring:
   profiles:
     active: 
       - dev
---
server:
  port:  8001

spring:
  profile: dev
  application:
    name : microserver-springcloud-eureka-provider
  datasource:
    username: root
    password: RW3CEZT56
    url: jdbc:mysql://localhost:3306/cloudDB01 
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-mills: 200 
  
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: 
    - classpath: mybatis/mapper/**/*.xml

eureka:
  instance:
    hostname: eureka7001.com
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
       
      
---
server:
  port: 8002
  
spring:
  profile: test
  application:
    name : microserver-springcloud-eureka-provider
  datasource:
    username: root
    password: RW3CEZT56
    url: jdbc:mysql://localhost:3306/cloudDB01 
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-mills: 200

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: 
    - classpath: mybatis/mapper/**/*.xml

eureka:
  instance:
    hostname: eureka7001.com
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
