spring:
   profiles:
     active: 
       - dev
---
server:
  port:  7001

spring:
  profile: dev
  application:
    name : microservice-springcloud-eureka-client

eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #服务端不需注册进eureka中
    fetch-registry: false  #不需要获取eureka的注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7002
  
spring: 
  profile: test
  application:
    name: microservice-springcloud-eureka-client

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server-url:
      defaultZone: http://eureka-dev.com:7002/eureka/
